package dpla.ingestion3.model

import dpla.ingestion3.messages.IngestMessage
import dpla.ingestion3.model.DplaMapData._
import org.json4s.{JNothing, JValue}

import scala.util.Try



/**
  * Contains type definitions that express cardinality of fields
  * and a union type for fields that can be literals or uris.
  */
object DplaMapData {
  type ZeroToMany[T] = Seq[T]
  type AtLeastOne[T] = Seq[T]
  type ZeroToOne[T] = Option[T]
  type ExactlyOne[T] = T
  type LiteralOrUri = Either[String, URI]
}

//Core Classes

/**
  * The aggregation of attributes that apply to the described resource as a whole,
  * grouped from edm:WebResource and dpla:SourceResource.
  *
  */
case class OreAggregation(
                           dplaUri: ExactlyOne[URI],
                           sourceResource: ExactlyOne[DplaSourceResource],
                           dataProvider: ExactlyOne[EdmAgent],
                           originalRecord: ExactlyOne[String],
                           hasView: ZeroToMany[EdmWebResource] = Seq(),
                           intermediateProvider: ZeroToOne[EdmAgent] = None,
                           isShownAt: ExactlyOne[EdmWebResource],
                           `object`: ZeroToOne[EdmWebResource] = None, // full size image
                           preview: ZeroToOne[EdmWebResource] = None, // thumbnail
                           provider: ExactlyOne[EdmAgent],
                           edmRights: ZeroToOne[URI] = None,
                           sidecar: JValue = JNothing,
                           messages: ZeroToMany[IngestMessage] = Seq[IngestMessage](),
                           originalId: ExactlyOne[String],
                           tags: ZeroToMany[URI] = Seq[URI](),
                           iiifManifest: ZeroToOne[URI] = None, // URL for IIIF presentation manifest
                           mediaMaster: ZeroToMany[EdmWebResource] = Seq() // master media representation of artifact

                         )

/**
  * dpla:SourceResource is a subclass of "edm:ProvidedCHO," which comprises the described resources
  * (in EDM called "cultural heritage objects") about which DPLA collects descriptions.
  * It is here that attributes of the described resources are located,
  * not the digital representations of them.
  */
case class DplaSourceResource(
                               alternateTitle: ZeroToMany[String] = Seq(),
                               collection: ZeroToMany[DcmiTypeCollection] = Seq(),
                               contributor: ZeroToMany[EdmAgent] = Seq(),
                               creator: ZeroToMany[EdmAgent] = Seq(),
                               date: ZeroToMany[EdmTimeSpan] = Seq(),
                               description: ZeroToMany[String] = Seq(),
                               extent: ZeroToMany[String] = Seq(),
                               format: ZeroToMany[String] = Seq(),
                               genre: ZeroToMany[SkosConcept] = Seq(),
                               identifier: ZeroToMany[String] = Seq(),
                               language: ZeroToMany[SkosConcept] = Seq(),
                               place: ZeroToMany[DplaPlace] = Seq(),
                               publisher: ZeroToMany[EdmAgent] = Seq(),
                               relation: ZeroToMany[LiteralOrUri] = Seq(),
                               replacedBy: ZeroToMany[String] = Seq(),
                               replaces: ZeroToMany[String] = Seq(),
                               rights: AtLeastOne[String] = Seq(),
                               rightsHolder: ZeroToMany[EdmAgent] = Seq(),
                               subject: ZeroToMany[SkosConcept] = Seq(),
                               temporal: ZeroToMany[EdmTimeSpan] = Seq(),
                               title: AtLeastOne[String] = Seq(),
                               `type`: ZeroToMany[String] = Seq() //todo should be URIs?
                             )


// Context Classes

case class EdmWebResource(
                           uri: ExactlyOne[URI],
                           fileFormat: ZeroToMany[String] = Seq(),
                           dcRights: ZeroToMany[String] = Seq(),
                           edmRights: ZeroToOne[String] = None, //todo should be a URI?
                           isReferencedBy: ZeroToOne[URI] = None
                         )


case class EdmAgent(
                     uri: ZeroToOne[URI] = None,
                     name: ZeroToOne[String] = None,
                     providedLabel: ZeroToOne[String] = None,
                     note: ZeroToOne[String] = None,
                     scheme: ZeroToOne[URI] = None,
                     exactMatch: ZeroToMany[URI] = Seq(),
                     closeMatch: ZeroToMany[URI] = Seq()
                   ) {
  def print: String = name.getOrElse("")
}

case class DcmiTypeCollection(
                               title: ZeroToOne[String] = None,
                               description: ZeroToOne[String] = None
                             )

case class SkosConcept(
                        concept: ZeroToOne[String] = None,
                        providedLabel: ZeroToOne[String] = None,
                        note: ZeroToOne[String] = None,
                        scheme: ZeroToOne[URI] = None,
                        exactMatch: ZeroToMany[URI] = Seq(),
                        closeMatch: ZeroToMany[URI] = Seq()
                      )

case class DplaPlace(
                      name: ZeroToOne[String] = None,
                      city: ZeroToOne[String] = None,
                      county: ZeroToOne[String] = None,
                      state: ZeroToOne[String] = None,
                      country: ZeroToOne[String] = None,
                      region: ZeroToOne[String] = None,
                      coordinates: ZeroToOne[String] = None
                    )

case class EdmTimeSpan(
                        originalSourceDate: ZeroToOne[String] = None,
                        prefLabel: ZeroToOne[String] = None,
                        begin: ZeroToOne[String] = None,
                        end: ZeroToOne[String] = None
                      )


case class URI(value: String) {
  def validate: Boolean = Try { new java.net.URI(value) }.isSuccess

  def isValidEdmRightsUri: Boolean = validEdmRightsValues.contains(value)

  /**

    * toString is overridden so that when URI values are extracted
    * the type is dropped. Otherwise calling URI("http://abc.com").toString()
    * will return URI("http://abc.com") when it should return "http://abc.com"
    *
    * @return String value
    */
  override def toString: String = value

  val validEdmRightsValues: Set[String] = Set(
    "http://rightsstatements.org/vocab/CNE/1.0/",
    "http://rightsstatements.org/vocab/InC-EDU/1.0/",
    "http://rightsstatements.org/vocab/InC-NC/1.0/",
    "http://rightsstatements.org/vocab/InC-OW-EU/1.0/",
    "http://rightsstatements.org/vocab/InC-RUU/1.0/",
    "http://rightsstatements.org/vocab/InC/1.0/",
    "http://rightsstatements.org/vocab/NKC/1.0/",
    "http://rightsstatements.org/vocab/NoC-CR/1.0/",
    "http://rightsstatements.org/vocab/NoC-NC/1.0/",
    "http://rightsstatements.org/vocab/NoC-OKLR/1.0/",
    "http://rightsstatements.org/vocab/NoC-US/1.0/",
    "http://rightsstatements.org/vocab/UND/1.0/",
    "http://creativecommons.org/licenses/BSD/",
    "http://creativecommons.org/licenses/by-nc-nd/1.0/",
    "http://creativecommons.org/licenses/by-nc-nd/2.0/",
    "http://creativecommons.org/licenses/by-nc-nd/2.0/at/",
    "http://creativecommons.org/licenses/by-nc-nd/2.0/au/",
    "http://creativecommons.org/licenses/by-nc-nd/2.0/be/",
    "http://creativecommons.org/licenses/by-nc-nd/2.0/br/",
    "http://creativecommons.org/licenses/by-nc-nd/2.0/ca/",
    "http://creativecommons.org/licenses/by-nc-nd/2.0/cl/",
    "http://creativecommons.org/licenses/by-nc-nd/2.0/de/",
    "http://creativecommons.org/licenses/by-nc-nd/2.0/es/",
    "http://creativecommons.org/licenses/by-nc-nd/2.0/fr/",
    "http://creativecommons.org/licenses/by-nc-nd/2.0/hr/",
    "http://creativecommons.org/licenses/by-nc-nd/2.0/it/",
    "http://creativecommons.org/licenses/by-nc-nd/2.0/jp/",
    "http://creativecommons.org/licenses/by-nc-nd/2.0/kr/",
    "http://creativecommons.org/licenses/by-nc-nd/2.0/nl/",
    "http://creativecommons.org/licenses/by-nc-nd/2.0/pl/",
    "http://creativecommons.org/licenses/by-nc-nd/2.0/tw/",
    "http://creativecommons.org/licenses/by-nc-nd/2.0/uk/",
    "http://creativecommons.org/licenses/by-nc-nd/2.0/za/",
    "http://creativecommons.org/licenses/by-nc-nd/2.5/",
    "http://creativecommons.org/licenses/by-nc-nd/2.5/ar/",
    "http://creativecommons.org/licenses/by-nc-nd/2.5/au/",
    "http://creativecommons.org/licenses/by-nc-nd/2.5/bg/",
    "http://creativecommons.org/licenses/by-nc-nd/2.5/br/",
    "http://creativecommons.org/licenses/by-nc-nd/2.5/ca/",
    "http://creativecommons.org/licenses/by-nc-nd/2.5/ch/",
    "http://creativecommons.org/licenses/by-nc-nd/2.5/cn/",
    "http://creativecommons.org/licenses/by-nc-nd/2.5/co/",
    "http://creativecommons.org/licenses/by-nc-nd/2.5/dk/",
    "http://creativecommons.org/licenses/by-nc-nd/2.5/es/",
    "http://creativecommons.org/licenses/by-nc-nd/2.5/hr/",
    "http://creativecommons.org/licenses/by-nc-nd/2.5/hu/",
    "http://creativecommons.org/licenses/by-nc-nd/2.5/il/",
    "http://creativecommons.org/licenses/by-nc-nd/2.5/in/",
    "http://creativecommons.org/licenses/by-nc-nd/2.5/it/",
    "http://creativecommons.org/licenses/by-nc-nd/2.5/mk/",
    "http://creativecommons.org/licenses/by-nc-nd/2.5/mt/",
    "http://creativecommons.org/licenses/by-nc-nd/2.5/mx/",
    "http://creativecommons.org/licenses/by-nc-nd/2.5/my/",
    "http://creativecommons.org/licenses/by-nc-nd/2.5/nl/",
    "http://creativecommons.org/licenses/by-nc-nd/2.5/pe/",
    "http://creativecommons.org/licenses/by-nc-nd/2.5/pl/",
    "http://creativecommons.org/licenses/by-nc-nd/2.5/pt/",
    "http://creativecommons.org/licenses/by-nc-nd/2.5/scotland/",
    "http://creativecommons.org/licenses/by-nc-nd/2.5/se/",
    "http://creativecommons.org/licenses/by-nc-nd/2.5/si/",
    "http://creativecommons.org/licenses/by-nc-nd/2.5/tw/",
    "http://creativecommons.org/licenses/by-nc-nd/2.5/za/",
    "http://creativecommons.org/licenses/by-nc-nd/3.0/",
    "http://creativecommons.org/licenses/by-nc-nd/3.0/at/",
    "http://creativecommons.org/licenses/by-nc-nd/3.0/au/",
    "http://creativecommons.org/licenses/by-nc-nd/3.0/br/",
    "http://creativecommons.org/licenses/by-nc-nd/3.0/ch/",
    "http://creativecommons.org/licenses/by-nc-nd/3.0/cl/",
    "http://creativecommons.org/licenses/by-nc-nd/3.0/cn/",
    "http://creativecommons.org/licenses/by-nc-nd/3.0/cr/",
    "http://creativecommons.org/licenses/by-nc-nd/3.0/cz/",
    "http://creativecommons.org/licenses/by-nc-nd/3.0/de/",
    "http://creativecommons.org/licenses/by-nc-nd/3.0/ec/",
    "http://creativecommons.org/licenses/by-nc-nd/3.0/ee/",
    "http://creativecommons.org/licenses/by-nc-nd/3.0/eg/",
    "http://creativecommons.org/licenses/by-nc-nd/3.0/es/",
    "http://creativecommons.org/licenses/by-nc-nd/3.0/fr/",
    "http://creativecommons.org/licenses/by-nc-nd/3.0/gr/",
    "http://creativecommons.org/licenses/by-nc-nd/3.0/gt/",
    "http://creativecommons.org/licenses/by-nc-nd/3.0/hk/",
    "http://creativecommons.org/licenses/by-nc-nd/3.0/hr/",
    "http://creativecommons.org/licenses/by-nc-nd/3.0/ie/",
    "http://creativecommons.org/licenses/by-nc-nd/3.0/igo/",
    "http://creativecommons.org/licenses/by-nc-nd/3.0/it/",
    "http://creativecommons.org/licenses/by-nc-nd/3.0/lu/",
    "http://creativecommons.org/licenses/by-nc-nd/3.0/nl/",
    "http://creativecommons.org/licenses/by-nc-nd/3.0/no/",
    "http://creativecommons.org/licenses/by-nc-nd/3.0/nz/",
    "http://creativecommons.org/licenses/by-nc-nd/3.0/ph/",
    "http://creativecommons.org/licenses/by-nc-nd/3.0/pl/",
    "http://creativecommons.org/licenses/by-nc-nd/3.0/pr/",
    "http://creativecommons.org/licenses/by-nc-nd/3.0/pt/",
    "http://creativecommons.org/licenses/by-nc-nd/3.0/ro/",
    "http://creativecommons.org/licenses/by-nc-nd/3.0/rs/",
    "http://creativecommons.org/licenses/by-nc-nd/3.0/sg/",
    "http://creativecommons.org/licenses/by-nc-nd/3.0/th/",
    "http://creativecommons.org/licenses/by-nc-nd/3.0/tw/",
    "http://creativecommons.org/licenses/by-nc-nd/3.0/ug/",
    "http://creativecommons.org/licenses/by-nc-nd/3.0/us/",
    "http://creativecommons.org/licenses/by-nc-nd/3.0/ve/",
    "http://creativecommons.org/licenses/by-nc-nd/3.0/vn/",
    "http://creativecommons.org/licenses/by-nc-nd/4.0/",
    "http://creativecommons.org/licenses/by-nc-sa/1.0/",
    "http://creativecommons.org/licenses/by-nc-sa/1.0/fi/",
    "http://creativecommons.org/licenses/by-nc-sa/1.0/il/",
    "http://creativecommons.org/licenses/by-nc-sa/1.0/nl/",
    "http://creativecommons.org/licenses/by-nc-sa/2.0/",
    "http://creativecommons.org/licenses/by-nc-sa/2.0/at/",
    "http://creativecommons.org/licenses/by-nc-sa/2.0/au/",
    "http://creativecommons.org/licenses/by-nc-sa/2.0/be/",
    "http://creativecommons.org/licenses/by-nc-sa/2.0/br/",
    "http://creativecommons.org/licenses/by-nc-sa/2.0/ca/",
    "http://creativecommons.org/licenses/by-nc-sa/2.0/cl/",
    "http://creativecommons.org/licenses/by-nc-sa/2.0/de/",
    "http://creativecommons.org/licenses/by-nc-sa/2.0/es/",
    "http://creativecommons.org/licenses/by-nc-sa/2.0/fr/",
    "http://creativecommons.org/licenses/by-nc-sa/2.0/hr/",
    "http://creativecommons.org/licenses/by-nc-sa/2.0/it/",
    "http://creativecommons.org/licenses/by-nc-sa/2.0/jp/",
    "http://creativecommons.org/licenses/by-nc-sa/2.0/kr/",
    "http://creativecommons.org/licenses/by-nc-sa/2.0/nl/",
    "http://creativecommons.org/licenses/by-nc-sa/2.0/pl/",
    "http://creativecommons.org/licenses/by-nc-sa/2.0/tw/",
    "http://creativecommons.org/licenses/by-nc-sa/2.0/uk/",
    "http://creativecommons.org/licenses/by-nc-sa/2.0/za/",
    "http://creativecommons.org/licenses/by-nc-sa/2.5/",
    "http://creativecommons.org/licenses/by-nc-sa/2.5/ar/",
    "http://creativecommons.org/licenses/by-nc-sa/2.5/au/",
    "http://creativecommons.org/licenses/by-nc-sa/2.5/bg/",
    "http://creativecommons.org/licenses/by-nc-sa/2.5/br/",
    "http://creativecommons.org/licenses/by-nc-sa/2.5/ca/",
    "http://creativecommons.org/licenses/by-nc-sa/2.5/ch/",
    "http://creativecommons.org/licenses/by-nc-sa/2.5/cn/",
    "http://creativecommons.org/licenses/by-nc-sa/2.5/co/",
    "http://creativecommons.org/licenses/by-nc-sa/2.5/dk/",
    "http://creativecommons.org/licenses/by-nc-sa/2.5/es/",
    "http://creativecommons.org/licenses/by-nc-sa/2.5/hr/",
    "http://creativecommons.org/licenses/by-nc-sa/2.5/hu/",
    "http://creativecommons.org/licenses/by-nc-sa/2.5/il/",
    "http://creativecommons.org/licenses/by-nc-sa/2.5/in/",
    "http://creativecommons.org/licenses/by-nc-sa/2.5/it/",
    "http://creativecommons.org/licenses/by-nc-sa/2.5/mk/",
    "http://creativecommons.org/licenses/by-nc-sa/2.5/mt/",
    "http://creativecommons.org/licenses/by-nc-sa/2.5/mx/",
    "http://creativecommons.org/licenses/by-nc-sa/2.5/my/",
    "http://creativecommons.org/licenses/by-nc-sa/2.5/nl/",
    "http://creativecommons.org/licenses/by-nc-sa/2.5/pe/",
    "http://creativecommons.org/licenses/by-nc-sa/2.5/pl/",
    "http://creativecommons.org/licenses/by-nc-sa/2.5/pt/",
    "http://creativecommons.org/licenses/by-nc-sa/2.5/scotland/",
    "http://creativecommons.org/licenses/by-nc-sa/2.5/se/",
    "http://creativecommons.org/licenses/by-nc-sa/2.5/si/",
    "http://creativecommons.org/licenses/by-nc-sa/2.5/tw/",
    "http://creativecommons.org/licenses/by-nc-sa/2.5/za/",
    "http://creativecommons.org/licenses/by-nc-sa/3.0/",
    "http://creativecommons.org/licenses/by-nc-sa/3.0/at/",
    "http://creativecommons.org/licenses/by-nc-sa/3.0/au/",
    "http://creativecommons.org/licenses/by-nc-sa/3.0/br/",
    "http://creativecommons.org/licenses/by-nc-sa/3.0/ch/",
    "http://creativecommons.org/licenses/by-nc-sa/3.0/cl/",
    "http://creativecommons.org/licenses/by-nc-sa/3.0/cn/",
    "http://creativecommons.org/licenses/by-nc-sa/3.0/cr/",
    "http://creativecommons.org/licenses/by-nc-sa/3.0/cz/",
    "http://creativecommons.org/licenses/by-nc-sa/3.0/de/",
    "http://creativecommons.org/licenses/by-nc-sa/3.0/ec/",
    "http://creativecommons.org/licenses/by-nc-sa/3.0/ee/",
    "http://creativecommons.org/licenses/by-nc-sa/3.0/eg/",
    "http://creativecommons.org/licenses/by-nc-sa/3.0/es/",
    "http://creativecommons.org/licenses/by-nc-sa/3.0/fr/",
    "http://creativecommons.org/licenses/by-nc-sa/3.0/gr/",
    "http://creativecommons.org/licenses/by-nc-sa/3.0/gt/",
    "http://creativecommons.org/licenses/by-nc-sa/3.0/hk/",
    "http://creativecommons.org/licenses/by-nc-sa/3.0/hr/",
    "http://creativecommons.org/licenses/by-nc-sa/3.0/ie/",
    "http://creativecommons.org/licenses/by-nc-sa/3.0/igo/",
    "http://creativecommons.org/licenses/by-nc-sa/3.0/it/",
    "http://creativecommons.org/licenses/by-nc-sa/3.0/lu/",
    "http://creativecommons.org/licenses/by-nc-sa/3.0/nl/",
    "http://creativecommons.org/licenses/by-nc-sa/3.0/no/",
    "http://creativecommons.org/licenses/by-nc-sa/3.0/nz/",
    "http://creativecommons.org/licenses/by-nc-sa/3.0/ph/",
    "http://creativecommons.org/licenses/by-nc-sa/3.0/pl/",
    "http://creativecommons.org/licenses/by-nc-sa/3.0/pr/",
    "http://creativecommons.org/licenses/by-nc-sa/3.0/pt/",
    "http://creativecommons.org/licenses/by-nc-sa/3.0/ro/",
    "http://creativecommons.org/licenses/by-nc-sa/3.0/rs/",
    "http://creativecommons.org/licenses/by-nc-sa/3.0/sg/",
    "http://creativecommons.org/licenses/by-nc-sa/3.0/th/",
    "http://creativecommons.org/licenses/by-nc-sa/3.0/tw/",
    "http://creativecommons.org/licenses/by-nc-sa/3.0/ug/",
    "http://creativecommons.org/licenses/by-nc-sa/3.0/us/",
    "http://creativecommons.org/licenses/by-nc-sa/3.0/ve/",
    "http://creativecommons.org/licenses/by-nc-sa/3.0/vn/",
    "http://creativecommons.org/licenses/by-nc-sa/4.0/",
    "http://creativecommons.org/licenses/by-nc/1.0/",
    "http://creativecommons.org/licenses/by-nc/1.0/fi/",
    "http://creativecommons.org/licenses/by-nc/1.0/il/",
    "http://creativecommons.org/licenses/by-nc/1.0/nl/",
    "http://creativecommons.org/licenses/by-nc/2.0/",
    "http://creativecommons.org/licenses/by-nc/2.0/at/",
    "http://creativecommons.org/licenses/by-nc/2.0/au/",
    "http://creativecommons.org/licenses/by-nc/2.0/be/",
    "http://creativecommons.org/licenses/by-nc/2.0/br/",
    "http://creativecommons.org/licenses/by-nc/2.0/ca/",
    "http://creativecommons.org/licenses/by-nc/2.0/cl/",
    "http://creativecommons.org/licenses/by-nc/2.0/de/",
    "http://creativecommons.org/licenses/by-nc/2.0/es/",
    "http://creativecommons.org/licenses/by-nc/2.0/fr/",
    "http://creativecommons.org/licenses/by-nc/2.0/hr/",
    "http://creativecommons.org/licenses/by-nc/2.0/it/",
    "http://creativecommons.org/licenses/by-nc/2.0/jp/",
    "http://creativecommons.org/licenses/by-nc/2.0/kr/",
    "http://creativecommons.org/licenses/by-nc/2.0/nl/",
    "http://creativecommons.org/licenses/by-nc/2.0/pl/",
    "http://creativecommons.org/licenses/by-nc/2.0/tw/",
    "http://creativecommons.org/licenses/by-nc/2.0/uk/",
    "http://creativecommons.org/licenses/by-nc/2.0/za/",
    "http://creativecommons.org/licenses/by-nc/2.5/",
    "http://creativecommons.org/licenses/by-nc/2.5/ar/",
    "http://creativecommons.org/licenses/by-nc/2.5/au/",
    "http://creativecommons.org/licenses/by-nc/2.5/bg/",
    "http://creativecommons.org/licenses/by-nc/2.5/br/",
    "http://creativecommons.org/licenses/by-nc/2.5/ca/",
    "http://creativecommons.org/licenses/by-nc/2.5/ch/",
    "http://creativecommons.org/licenses/by-nc/2.5/cn/",
    "http://creativecommons.org/licenses/by-nc/2.5/co/",
    "http://creativecommons.org/licenses/by-nc/2.5/dk/",
    "http://creativecommons.org/licenses/by-nc/2.5/es/",
    "http://creativecommons.org/licenses/by-nc/2.5/hr/",
    "http://creativecommons.org/licenses/by-nc/2.5/hu/",
    "http://creativecommons.org/licenses/by-nc/2.5/il/",
    "http://creativecommons.org/licenses/by-nc/2.5/in/",
    "http://creativecommons.org/licenses/by-nc/2.5/it/",
    "http://creativecommons.org/licenses/by-nc/2.5/mk/",
    "http://creativecommons.org/licenses/by-nc/2.5/mt/",
    "http://creativecommons.org/licenses/by-nc/2.5/mx/",
    "http://creativecommons.org/licenses/by-nc/2.5/my/",
    "http://creativecommons.org/licenses/by-nc/2.5/nl/",
    "http://creativecommons.org/licenses/by-nc/2.5/pe/",
    "http://creativecommons.org/licenses/by-nc/2.5/pl/",
    "http://creativecommons.org/licenses/by-nc/2.5/pt/",
    "http://creativecommons.org/licenses/by-nc/2.5/scotland/",
    "http://creativecommons.org/licenses/by-nc/2.5/se/",
    "http://creativecommons.org/licenses/by-nc/2.5/si/",
    "http://creativecommons.org/licenses/by-nc/2.5/tw/",
    "http://creativecommons.org/licenses/by-nc/2.5/za/",
    "http://creativecommons.org/licenses/by-nc/3.0/",
    "http://creativecommons.org/licenses/by-nc/3.0/at/",
    "http://creativecommons.org/licenses/by-nc/3.0/au/",
    "http://creativecommons.org/licenses/by-nc/3.0/br/",
    "http://creativecommons.org/licenses/by-nc/3.0/ch/",
    "http://creativecommons.org/licenses/by-nc/3.0/cl/",
    "http://creativecommons.org/licenses/by-nc/3.0/cn/",
    "http://creativecommons.org/licenses/by-nc/3.0/cr/",
    "http://creativecommons.org/licenses/by-nc/3.0/cz/",
    "http://creativecommons.org/licenses/by-nc/3.0/de/",
    "http://creativecommons.org/licenses/by-nc/3.0/ec/",
    "http://creativecommons.org/licenses/by-nc/3.0/ee/",
    "http://creativecommons.org/licenses/by-nc/3.0/eg/",
    "http://creativecommons.org/licenses/by-nc/3.0/es/",
    "http://creativecommons.org/licenses/by-nc/3.0/fr/",
    "http://creativecommons.org/licenses/by-nc/3.0/gr/",
    "http://creativecommons.org/licenses/by-nc/3.0/gt/",
    "http://creativecommons.org/licenses/by-nc/3.0/hk/",
    "http://creativecommons.org/licenses/by-nc/3.0/hr/",
    "http://creativecommons.org/licenses/by-nc/3.0/ie/",
    "http://creativecommons.org/licenses/by-nc/3.0/igo/",
    "http://creativecommons.org/licenses/by-nc/3.0/it/",
    "http://creativecommons.org/licenses/by-nc/3.0/lu/",
    "http://creativecommons.org/licenses/by-nc/3.0/nl/",
    "http://creativecommons.org/licenses/by-nc/3.0/no/",
    "http://creativecommons.org/licenses/by-nc/3.0/nz/",
    "http://creativecommons.org/licenses/by-nc/3.0/ph/",
    "http://creativecommons.org/licenses/by-nc/3.0/pl/",
    "http://creativecommons.org/licenses/by-nc/3.0/pr/",
    "http://creativecommons.org/licenses/by-nc/3.0/pt/",
    "http://creativecommons.org/licenses/by-nc/3.0/ro/",
    "http://creativecommons.org/licenses/by-nc/3.0/rs/",
    "http://creativecommons.org/licenses/by-nc/3.0/sg/",
    "http://creativecommons.org/licenses/by-nc/3.0/th/",
    "http://creativecommons.org/licenses/by-nc/3.0/tw/",
    "http://creativecommons.org/licenses/by-nc/3.0/ug/",
    "http://creativecommons.org/licenses/by-nc/3.0/us/",
    "http://creativecommons.org/licenses/by-nc/3.0/ve/",
    "http://creativecommons.org/licenses/by-nc/3.0/vn/",
    "http://creativecommons.org/licenses/by-nc/4.0/",
    "http://creativecommons.org/licenses/by-nd-nc/1.0/",
    "http://creativecommons.org/licenses/by-nd-nc/1.0/fi/",
    "http://creativecommons.org/licenses/by-nd-nc/1.0/il/",
    "http://creativecommons.org/licenses/by-nd-nc/1.0/nl/",
    "http://creativecommons.org/licenses/by-nd-nc/2.0/jp/",
    "http://creativecommons.org/licenses/by-nd/1.0/",
    "http://creativecommons.org/licenses/by-nd/1.0/fi/",
    "http://creativecommons.org/licenses/by-nd/1.0/il/",
    "http://creativecommons.org/licenses/by-nd/1.0/nl/",
    "http://creativecommons.org/licenses/by-nd/2.0/",
    "http://creativecommons.org/licenses/by-nd/2.0/at/",
    "http://creativecommons.org/licenses/by-nd/2.0/au/",
    "http://creativecommons.org/licenses/by-nd/2.0/be/",
    "http://creativecommons.org/licenses/by-nd/2.0/br/",
    "http://creativecommons.org/licenses/by-nd/2.0/ca/",
    "http://creativecommons.org/licenses/by-nd/2.0/cl/",
    "http://creativecommons.org/licenses/by-nd/2.0/de/",
    "http://creativecommons.org/licenses/by-nd/2.0/es/",
    "http://creativecommons.org/licenses/by-nd/2.0/fr/",
    "http://creativecommons.org/licenses/by-nd/2.0/hr/",
    "http://creativecommons.org/licenses/by-nd/2.0/it/",
    "http://creativecommons.org/licenses/by-nd/2.0/jp/",
    "http://creativecommons.org/licenses/by-nd/2.0/kr/",
    "http://creativecommons.org/licenses/by-nd/2.0/nl/",
    "http://creativecommons.org/licenses/by-nd/2.0/pl/",
    "http://creativecommons.org/licenses/by-nd/2.0/tw/",
    "http://creativecommons.org/licenses/by-nd/2.0/uk/",
    "http://creativecommons.org/licenses/by-nd/2.0/za/",
    "http://creativecommons.org/licenses/by-nd/2.5/",
    "http://creativecommons.org/licenses/by-nd/2.5/ar/",
    "http://creativecommons.org/licenses/by-nd/2.5/au/",
    "http://creativecommons.org/licenses/by-nd/2.5/bg/",
    "http://creativecommons.org/licenses/by-nd/2.5/br/",
    "http://creativecommons.org/licenses/by-nd/2.5/ca/",
    "http://creativecommons.org/licenses/by-nd/2.5/ch/",
    "http://creativecommons.org/licenses/by-nd/2.5/cn/",
    "http://creativecommons.org/licenses/by-nd/2.5/co/",
    "http://creativecommons.org/licenses/by-nd/2.5/dk/",
    "http://creativecommons.org/licenses/by-nd/2.5/es/",
    "http://creativecommons.org/licenses/by-nd/2.5/hr/",
    "http://creativecommons.org/licenses/by-nd/2.5/hu/",
    "http://creativecommons.org/licenses/by-nd/2.5/il/",
    "http://creativecommons.org/licenses/by-nd/2.5/in/",
    "http://creativecommons.org/licenses/by-nd/2.5/it/",
    "http://creativecommons.org/licenses/by-nd/2.5/mk/",
    "http://creativecommons.org/licenses/by-nd/2.5/mt/",
    "http://creativecommons.org/licenses/by-nd/2.5/mx/",
    "http://creativecommons.org/licenses/by-nd/2.5/my/",
    "http://creativecommons.org/licenses/by-nd/2.5/nl/",
    "http://creativecommons.org/licenses/by-nd/2.5/pe/",
    "http://creativecommons.org/licenses/by-nd/2.5/pl/",
    "http://creativecommons.org/licenses/by-nd/2.5/pt/",
    "http://creativecommons.org/licenses/by-nd/2.5/scotland/",
    "http://creativecommons.org/licenses/by-nd/2.5/se/",
    "http://creativecommons.org/licenses/by-nd/2.5/si/",
    "http://creativecommons.org/licenses/by-nd/2.5/tw/",
    "http://creativecommons.org/licenses/by-nd/2.5/za/",
    "http://creativecommons.org/licenses/by-nd/3.0/",
    "http://creativecommons.org/licenses/by-nd/3.0/at/",
    "http://creativecommons.org/licenses/by-nd/3.0/au/",
    "http://creativecommons.org/licenses/by-nd/3.0/br/",
    "http://creativecommons.org/licenses/by-nd/3.0/ch/",
    "http://creativecommons.org/licenses/by-nd/3.0/cl/",
    "http://creativecommons.org/licenses/by-nd/3.0/cn/",
    "http://creativecommons.org/licenses/by-nd/3.0/cr/",
    "http://creativecommons.org/licenses/by-nd/3.0/cz/",
    "http://creativecommons.org/licenses/by-nd/3.0/de/",
    "http://creativecommons.org/licenses/by-nd/3.0/ec/",
    "http://creativecommons.org/licenses/by-nd/3.0/ee/",
    "http://creativecommons.org/licenses/by-nd/3.0/eg/",
    "http://creativecommons.org/licenses/by-nd/3.0/es/",
    "http://creativecommons.org/licenses/by-nd/3.0/fr/",
    "http://creativecommons.org/licenses/by-nd/3.0/gr/",
    "http://creativecommons.org/licenses/by-nd/3.0/gt/",
    "http://creativecommons.org/licenses/by-nd/3.0/hk/",
    "http://creativecommons.org/licenses/by-nd/3.0/hr/",
    "http://creativecommons.org/licenses/by-nd/3.0/ie/",
    "http://creativecommons.org/licenses/by-nd/3.0/igo/",
    "http://creativecommons.org/licenses/by-nd/3.0/it/",
    "http://creativecommons.org/licenses/by-nd/3.0/lu/",
    "http://creativecommons.org/licenses/by-nd/3.0/nl/",
    "http://creativecommons.org/licenses/by-nd/3.0/no/",
    "http://creativecommons.org/licenses/by-nd/3.0/nz/",
    "http://creativecommons.org/licenses/by-nd/3.0/ph/",
    "http://creativecommons.org/licenses/by-nd/3.0/pl/",
    "http://creativecommons.org/licenses/by-nd/3.0/pr/",
    "http://creativecommons.org/licenses/by-nd/3.0/pt/",
    "http://creativecommons.org/licenses/by-nd/3.0/ro/",
    "http://creativecommons.org/licenses/by-nd/3.0/rs/",
    "http://creativecommons.org/licenses/by-nd/3.0/sg/",
    "http://creativecommons.org/licenses/by-nd/3.0/th/",
    "http://creativecommons.org/licenses/by-nd/3.0/tw/",
    "http://creativecommons.org/licenses/by-nd/3.0/ug/",
    "http://creativecommons.org/licenses/by-nd/3.0/us/",
    "http://creativecommons.org/licenses/by-nd/3.0/ve/",
    "http://creativecommons.org/licenses/by-nd/3.0/vn/",
    "http://creativecommons.org/licenses/by-nd/4.0/",
    "http://creativecommons.org/licenses/by-sa/1.0/",
    "http://creativecommons.org/licenses/by-sa/1.0/fi/",
    "http://creativecommons.org/licenses/by-sa/1.0/il/",
    "http://creativecommons.org/licenses/by-sa/1.0/nl/",
    "http://creativecommons.org/licenses/by-sa/2.0/",
    "http://creativecommons.org/licenses/by-sa/2.0/at/",
    "http://creativecommons.org/licenses/by-sa/2.0/au/",
    "http://creativecommons.org/licenses/by-sa/2.0/be/",
    "http://creativecommons.org/licenses/by-sa/2.0/br/",
    "http://creativecommons.org/licenses/by-sa/2.0/ca/",
    "http://creativecommons.org/licenses/by-sa/2.0/cl/",
    "http://creativecommons.org/licenses/by-sa/2.0/de/",
    "http://creativecommons.org/licenses/by-sa/2.0/es/",
    "http://creativecommons.org/licenses/by-sa/2.0/fr/",
    "http://creativecommons.org/licenses/by-sa/2.0/hr/",
    "http://creativecommons.org/licenses/by-sa/2.0/it/",
    "http://creativecommons.org/licenses/by-sa/2.0/jp/",
    "http://creativecommons.org/licenses/by-sa/2.0/kr/",
    "http://creativecommons.org/licenses/by-sa/2.0/nl/",
    "http://creativecommons.org/licenses/by-sa/2.0/pl/",
    "http://creativecommons.org/licenses/by-sa/2.0/tw/",
    "http://creativecommons.org/licenses/by-sa/2.0/uk/",
    "http://creativecommons.org/licenses/by-sa/2.0/za/",
    "http://creativecommons.org/licenses/by-sa/2.5/",
    "http://creativecommons.org/licenses/by-sa/2.5/ar/",
    "http://creativecommons.org/licenses/by-sa/2.5/au/",
    "http://creativecommons.org/licenses/by-sa/2.5/bg/",
    "http://creativecommons.org/licenses/by-sa/2.5/br/",
    "http://creativecommons.org/licenses/by-sa/2.5/ca/",
    "http://creativecommons.org/licenses/by-sa/2.5/ch/",
    "http://creativecommons.org/licenses/by-sa/2.5/cn/",
    "http://creativecommons.org/licenses/by-sa/2.5/co/",
    "http://creativecommons.org/licenses/by-sa/2.5/dk/",
    "http://creativecommons.org/licenses/by-sa/2.5/es/",
    "http://creativecommons.org/licenses/by-sa/2.5/hr/",
    "http://creativecommons.org/licenses/by-sa/2.5/hu/",
    "http://creativecommons.org/licenses/by-sa/2.5/il/",
    "http://creativecommons.org/licenses/by-sa/2.5/in/",
    "http://creativecommons.org/licenses/by-sa/2.5/it/",
    "http://creativecommons.org/licenses/by-sa/2.5/mk/",
    "http://creativecommons.org/licenses/by-sa/2.5/mt/",
    "http://creativecommons.org/licenses/by-sa/2.5/mx/",
    "http://creativecommons.org/licenses/by-sa/2.5/my/",
    "http://creativecommons.org/licenses/by-sa/2.5/nl/",
    "http://creativecommons.org/licenses/by-sa/2.5/pe/",
    "http://creativecommons.org/licenses/by-sa/2.5/pl/",
    "http://creativecommons.org/licenses/by-sa/2.5/pt/",
    "http://creativecommons.org/licenses/by-sa/2.5/scotland/",
    "http://creativecommons.org/licenses/by-sa/2.5/se/",
    "http://creativecommons.org/licenses/by-sa/2.5/si/",
    "http://creativecommons.org/licenses/by-sa/2.5/tw/",
    "http://creativecommons.org/licenses/by-sa/2.5/za/",
    "http://creativecommons.org/licenses/by-sa/3.0/",
    "http://creativecommons.org/licenses/by-sa/3.0/at/",
    "http://creativecommons.org/licenses/by-sa/3.0/au/",
    "http://creativecommons.org/licenses/by-sa/3.0/br/",
    "http://creativecommons.org/licenses/by-sa/3.0/ch/",
    "http://creativecommons.org/licenses/by-sa/3.0/cl/",
    "http://creativecommons.org/licenses/by-sa/3.0/cn/",
    "http://creativecommons.org/licenses/by-sa/3.0/cr/",
    "http://creativecommons.org/licenses/by-sa/3.0/cz/",
    "http://creativecommons.org/licenses/by-sa/3.0/de/",
    "http://creativecommons.org/licenses/by-sa/3.0/ec/",
    "http://creativecommons.org/licenses/by-sa/3.0/ee/",
    "http://creativecommons.org/licenses/by-sa/3.0/eg/",
    "http://creativecommons.org/licenses/by-sa/3.0/es/",
    "http://creativecommons.org/licenses/by-sa/3.0/fr/",
    "http://creativecommons.org/licenses/by-sa/3.0/gr/",
    "http://creativecommons.org/licenses/by-sa/3.0/gt/",
    "http://creativecommons.org/licenses/by-sa/3.0/hk/",
    "http://creativecommons.org/licenses/by-sa/3.0/hr/",
    "http://creativecommons.org/licenses/by-sa/3.0/ie/",
    "http://creativecommons.org/licenses/by-sa/3.0/igo/",
    "http://creativecommons.org/licenses/by-sa/3.0/it/",
    "http://creativecommons.org/licenses/by-sa/3.0/lu/",
    "http://creativecommons.org/licenses/by-sa/3.0/nl/",
    "http://creativecommons.org/licenses/by-sa/3.0/no/",
    "http://creativecommons.org/licenses/by-sa/3.0/nz/",
    "http://creativecommons.org/licenses/by-sa/3.0/ph/",
    "http://creativecommons.org/licenses/by-sa/3.0/pl/",
    "http://creativecommons.org/licenses/by-sa/3.0/pr/",
    "http://creativecommons.org/licenses/by-sa/3.0/pt/",
    "http://creativecommons.org/licenses/by-sa/3.0/ro/",
    "http://creativecommons.org/licenses/by-sa/3.0/rs/",
    "http://creativecommons.org/licenses/by-sa/3.0/sg/",
    "http://creativecommons.org/licenses/by-sa/3.0/th/",
    "http://creativecommons.org/licenses/by-sa/3.0/tw/",
    "http://creativecommons.org/licenses/by-sa/3.0/ug/",
    "http://creativecommons.org/licenses/by-sa/3.0/us/",
    "http://creativecommons.org/licenses/by-sa/3.0/ve/",
    "http://creativecommons.org/licenses/by-sa/3.0/vn/",
    "http://creativecommons.org/licenses/by-sa/4.0/",
    "http://creativecommons.org/licenses/by/1.0/",
    "http://creativecommons.org/licenses/by/1.0/fi/",
    "http://creativecommons.org/licenses/by/1.0/il/",
    "http://creativecommons.org/licenses/by/1.0/nl/",
    "http://creativecommons.org/licenses/by/2.0/",
    "http://creativecommons.org/licenses/by/2.0/at/",
    "http://creativecommons.org/licenses/by/2.0/au/",
    "http://creativecommons.org/licenses/by/2.0/be/",
    "http://creativecommons.org/licenses/by/2.0/br/",
    "http://creativecommons.org/licenses/by/2.0/ca/",
    "http://creativecommons.org/licenses/by/2.0/cl/",
    "http://creativecommons.org/licenses/by/2.0/de/",
    "http://creativecommons.org/licenses/by/2.0/es/",
    "http://creativecommons.org/licenses/by/2.0/fr/",
    "http://creativecommons.org/licenses/by/2.0/hr/",
    "http://creativecommons.org/licenses/by/2.0/it/",
    "http://creativecommons.org/licenses/by/2.0/jp/",
    "http://creativecommons.org/licenses/by/2.0/kr/",
    "http://creativecommons.org/licenses/by/2.0/nl/",
    "http://creativecommons.org/licenses/by/2.0/pl/",
    "http://creativecommons.org/licenses/by/2.0/tw/",
    "http://creativecommons.org/licenses/by/2.0/uk/",
    "http://creativecommons.org/licenses/by/2.0/za/",
    "http://creativecommons.org/licenses/by/2.5/",
    "http://creativecommons.org/licenses/by/2.5/ar/",
    "http://creativecommons.org/licenses/by/2.5/au/",
    "http://creativecommons.org/licenses/by/2.5/bg/",
    "http://creativecommons.org/licenses/by/2.5/br/",
    "http://creativecommons.org/licenses/by/2.5/ca/",
    "http://creativecommons.org/licenses/by/2.5/ch/",
    "http://creativecommons.org/licenses/by/2.5/cn/",
    "http://creativecommons.org/licenses/by/2.5/co/",
    "http://creativecommons.org/licenses/by/2.5/dk/",
    "http://creativecommons.org/licenses/by/2.5/es/",
    "http://creativecommons.org/licenses/by/2.5/hr/",
    "http://creativecommons.org/licenses/by/2.5/hu/",
    "http://creativecommons.org/licenses/by/2.5/il/",
    "http://creativecommons.org/licenses/by/2.5/in/",
    "http://creativecommons.org/licenses/by/2.5/it/",
    "http://creativecommons.org/licenses/by/2.5/mk/",
    "http://creativecommons.org/licenses/by/2.5/mt/",
    "http://creativecommons.org/licenses/by/2.5/mx/",
    "http://creativecommons.org/licenses/by/2.5/my/",
    "http://creativecommons.org/licenses/by/2.5/nl/",
    "http://creativecommons.org/licenses/by/2.5/pe/",
    "http://creativecommons.org/licenses/by/2.5/pl/",
    "http://creativecommons.org/licenses/by/2.5/pt/",
    "http://creativecommons.org/licenses/by/2.5/scotland/",
    "http://creativecommons.org/licenses/by/2.5/se/",
    "http://creativecommons.org/licenses/by/2.5/si/",
    "http://creativecommons.org/licenses/by/2.5/tw/",
    "http://creativecommons.org/licenses/by/2.5/za/",
    "http://creativecommons.org/licenses/by/3.0/",
    "http://creativecommons.org/licenses/by/3.0/at/",
    "http://creativecommons.org/licenses/by/3.0/au/",
    "http://creativecommons.org/licenses/by/3.0/br/",
    "http://creativecommons.org/licenses/by/3.0/ch/",
    "http://creativecommons.org/licenses/by/3.0/cl/",
    "http://creativecommons.org/licenses/by/3.0/cn/",
    "http://creativecommons.org/licenses/by/3.0/cr/",
    "http://creativecommons.org/licenses/by/3.0/cz/",
    "http://creativecommons.org/licenses/by/3.0/de/",
    "http://creativecommons.org/licenses/by/3.0/ec/",
    "http://creativecommons.org/licenses/by/3.0/ee/",
    "http://creativecommons.org/licenses/by/3.0/eg/",
    "http://creativecommons.org/licenses/by/3.0/es/",
    "http://creativecommons.org/licenses/by/3.0/fr/",
    "http://creativecommons.org/licenses/by/3.0/gr/",
    "http://creativecommons.org/licenses/by/3.0/gt/",
    "http://creativecommons.org/licenses/by/3.0/hk/",
    "http://creativecommons.org/licenses/by/3.0/hr/",
    "http://creativecommons.org/licenses/by/3.0/ie/",
    "http://creativecommons.org/licenses/by/3.0/igo/",
    "http://creativecommons.org/licenses/by/3.0/it/",
    "http://creativecommons.org/licenses/by/3.0/lu/",
    "http://creativecommons.org/licenses/by/3.0/nl/",
    "http://creativecommons.org/licenses/by/3.0/no/",
    "http://creativecommons.org/licenses/by/3.0/nz/",
    "http://creativecommons.org/licenses/by/3.0/ph/",
    "http://creativecommons.org/licenses/by/3.0/pl/",
    "http://creativecommons.org/licenses/by/3.0/pr/",
    "http://creativecommons.org/licenses/by/3.0/pt/",
    "http://creativecommons.org/licenses/by/3.0/ro/",
    "http://creativecommons.org/licenses/by/3.0/rs/",
    "http://creativecommons.org/licenses/by/3.0/sg/",
    "http://creativecommons.org/licenses/by/3.0/th/",
    "http://creativecommons.org/licenses/by/3.0/tw/",
    "http://creativecommons.org/licenses/by/3.0/ug/",
    "http://creativecommons.org/licenses/by/3.0/us/",
    "http://creativecommons.org/licenses/by/3.0/ve/",
    "http://creativecommons.org/licenses/by/3.0/vn/",
    "http://creativecommons.org/licenses/by/4.0/",
    "http://creativecommons.org/licenses/GPL/2.0/",
    "http://creativecommons.org/licenses/LGPL/2.1/",
    "http://creativecommons.org/licenses/MIT/",
    "http://creativecommons.org/licenses/nc-sa/1.0/",
    "http://creativecommons.org/licenses/nc-sa/1.0/fi/",
    "http://creativecommons.org/licenses/nc-sa/1.0/nl/",
    "http://creativecommons.org/licenses/nc-sa/2.0/jp/",
    "http://creativecommons.org/licenses/nc/1.0/",
    "http://creativecommons.org/licenses/nc/1.0/fi/",
    "http://creativecommons.org/licenses/nc/1.0/nl/",
    "http://creativecommons.org/licenses/nc/2.0/jp/",
    "http://creativecommons.org/licenses/nd/1.0/",
    "http://creativecommons.org/licenses/nd/1.0/fi/",
    "http://creativecommons.org/licenses/nd/1.0/nl/",
    "http://creativecommons.org/licenses/nd/2.0/jp/",
    "http://creativecommons.org/licenses/publicdomain/",
    "http://creativecommons.org/licenses/sa/1.0/",
    "http://creativecommons.org/licenses/sa/1.0/fi/",
    "http://creativecommons.org/licenses/sa/1.0/nl/",
    "http://creativecommons.org/licenses/sa/2.0/jp/",
    "http://creativecommons.org/licenses/sampling/1.0/",
    "http://creativecommons.org/licenses/sampling/1.0/br/",
    "http://creativecommons.org/licenses/sampling/1.0/tw/",
    "http://creativecommons.org/publicdomain/mark/1.0/",
    "http://creativecommons.org/publicdomain/zero/1.0/"
  )
}