name: Scala CI
on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-22.04 #temporary not latest because 24 is broken
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup JDK
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4.8.0
        with:
          distribution: temurin
          java-version: 11
          cache: sbt
      - name: Run tests
        run: sbt clean coverage test coverageReport
